spin_manifest_version = 2

[application]
authors = ["garrard"]
description = ""
name = "helloworld"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "helloworld"

[component.helloworld]
source = "target/helloworld.wasm"
exclude_files = ["**/node_modules"]
[component.helloworld.build]
command = "npm run build"
